### ISSUE TITLE
Statikus analízis eszköz futtatása és jelzett hibák átnézése

### ISSUE THREAD

**Issue by nemesmatyi** [BME-MIT-IET/The-Rabbit-Slayers-iet-2019#2]

**Comment by jszorfi** [comment]
Hétfőn kipróbáltuk a sonarQube-ot (8 bug, 441 code smell), és feltettük repoba, hogy a többieknek csak le kelljen húznia, használathoz csináltunk how-to-t.

**Comment by jszorfi** [comment]
A sonarQube mindig új adatokat generál, amire nyilván nem volt szüksége a többieknek a futtatáshoz, ezért ezeket .gitignore-ba tettük, hogy feleslegesen ne pusholjunk.

**Comment by jszorfi** [comment]
Több próbálkozás után sem sikerült elérni, hogy a git tényleg minden ignoráljon az adott mappákból, így eltávolítottuk a sonarQubet, és mindenki kézzel felrakta a repóján kívülre, hogy ne legyen belőle felesleges push forgalom.

**Comment by nemesmatyi** [comment]
KIosztottuk, hogy ki melyik mappában fogja a bugokat code smelleket ellenőrizni. A beoszts a következő:

RDFSharp/Query: Matyi
RDFSharp/Model: Márton
RDFSharp/Model/Serializers: Jázmin
Egyéb: Milán

**Comment by nemesmatyi** [comment]
Átnéztem a nekem kijelölt részt, és javítottam a code smellek egy részét (nálam bug nem volt). Ezeket a QueryCodeSmellFix branchen végeztem, és a pull request a következő:
https://github.com/BME-MIT-IET/The-Rabbit-Slayers-iet-2019/pull/5

**Comment by jszorfi** [comment]
Approvoltam Matyi munkáját.
Átnéztem a részemet, 2 fajta smellt javítottam, a többit indokoltam: [branch](https://github.com/BME-MIT-IET/The-Rabbit-Slayers-iet-2019/tree/ModelSerializersCodeSmellFix), [pull request](https://github.com/BME-MIT-IET/The-Rabbit-Slayers-iet-2019/pull/6)

Megírtam a wiki részem, a már meglévőekben javítottam formázást. A kód beillesztés furán működik, ha bárki tudja, javítsa bátran a részemet.

**Comment by jszorfi** [comment]
@nemesmatyi a wikid edit módban nagyon szép (intendált felsorolás) , de megtelítéskor csak folyó szöveg lett belőle, esetleg átformázhatod. (Type: Code smell, Severity: Minor)

**Comment by jszorfi** [comment]
Megtaláltam a code formázást, helyre raktam.

**Comment by nemesmatyi** [comment]
Approvoltam @jszorfi pull requestét, és rendbeszedtem a wikin felsorolást, amit multkor csináltam

**Comment by zalavari** [comment]
Elvégeztem a Model mappára vonatkozó Code Smell vizsgálatot, a wikit frissítettem.

**Comment by zalavari** [comment]
Beraktam egy új képet a wikire a SonarQube új eredményéről.
